[package]
name = "asteroids"
version = "2.0.0"
edition = "2021"
authors = ["Nova King <technobaboo@proton.me>"]
description = "Declarative UI for Stardust XR"
license = "MIT"
repository = "https://github.com/StardustXR/asteroids/"
homepage = "https://stardustxr.org"

[dependencies]
glam = { version = "0.24.1", features = ["mint"] }
mint = "0.5.9"
manifest-dir-macros = "0.1.17"
lazy_static = "1.4.0"
tokio = { version = "1.28.0", features = ["full"] }
input-event-codes = "5.16.8"
rustc-hash = "1.1.0"
# color-eyre = "0.6.2"
color-rs = "0.8.0"
serde = { version = "1.0.197", features = ["serde_derive"] }
slotmap = "1.0.7"
derive_setters = "0.1.6"
# colorgrad = "0.6.2"
# map-range = "0.1.2"

[dependencies.stardust-xr-fusion]
git = "https://github.com/StardustXR/core.git"
# path = "../../core/fusion"

[dependencies.stardust-xr-molecules]
git = "https://github.com/StardustXR/molecules.git"
# path = "../../molecules"
